name: Build latest from main branch
on:
  push:
    branches:
      - main

jobs:
  publish_github:
    name: Build latest and publish to ghcr
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s
      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: hello-cloud-run
          image: us-docker.pkg.dev/cloudrun/container/hello