name: Build latest from main branch
on:
  push:
    branches:
      - main
    paths:
      - main.go
      - go.mod
      - go.sum
      - pkg/**
      - .github/workflows/main.yaml


env:
  ko_version: 0.15.1

jobs:
  publish_github:
    name: Build latest and publish to ghcr
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go 1.x
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ^1.21

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...

      - name: Install KO
        run: |
          curl -L https://github.com/google/ko/releases/download/v${{ env.ko_version }}/ko_${{ env.ko_version }}_Linux_x86_64.tar.gz | tar xzf - ko
          chmod +x ./ko
      - name: Publish docker image
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
        run: |
          ./ko login ghcr.io --username $GITHUB_REPOSITORY_OWNER --password ${{ secrets.GITHUB_TOKEN }}
          ./ko build -B .
  publish_google:
    name: Build latest and publish to pkg.dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go 1.x
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ^1.21

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...

      - name: Install KO
        run: |
          curl -L https://github.com/google/ko/releases/download/v${{ env.ko_version }}/ko_${{ env.ko_version }}_Linux_x86_64.tar.gz | tar xzf - ko
          chmod +x ./ko
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Publish docker image
        env:
          KO_DOCKER_REPO: europe-north1-docker.pkg.dev/cloud-418/mope
        run: |
          ./ko login europe-north1-docker.pkg.dev --username oauth2accesstoken --password ${{ steps.auth.outputs.access_token }}
          ./ko build -B .
