name: Build and test
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - main.go
      - go.mod
      - go.sum
      - pkg/**
      - .github/workflows/pullrequest.yaml

jobs:
  test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go 1.x
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ^1.21

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...
