name: Build and test
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - main.go
      - go.mod
      - go.sum
      - pkg/**
      - .github/workflows/pullrequest.yaml

jobs:
  test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...
