name: Build release from tag
on:
  push:
    tags:
      - 'v*.*.*'

env:
  ko_version: 0.12.0

jobs:
  publish_github:
    name: Build latest and publish to ghcr
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Get version from tags
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...

      - name: Install KO
        run: |
          curl -L https://github.com/google/ko/releases/download/v${{ env.ko_version }}/ko_${{ env.ko_version }}_Linux_x86_64.tar.gz | tar xzf - ko
          chmod +x ./ko
      - name: Publish docker image
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
        run: |
          ./ko login ghcr.io --username $GITHUB_REPOSITORY_OWNER --password ${{ secrets.GITHUB_TOKEN }}
          ./ko publish -B --tags ${{ steps.version.outputs.tag }} .
  publish_google:
    name: Build latest and publish to pkg.dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get version from tags
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...

      - name: Install KO
        run: |
          curl -L https://github.com/google/ko/releases/download/v${{ env.ko_version }}/ko_${{ env.ko_version }}_Linux_x86_64.tar.gz | tar xzf - ko
          chmod +x ./ko
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Publish docker image
        env:
          KO_DOCKER_REPO: europe-north1-docker.pkg.dev/cloud-418/mope
        run: |
          ./ko login europe-north1-docker.pkg.dev --username oauth2accesstoken --password ${{ steps.auth.outputs.access_token }}
          ./ko publish -B --tags ${{ steps.version.outputs.tag }} .
      - name: Authenticate with Google Cloud
        id: runauth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_RUN_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s
      - name: Deploy release to cloud run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: mope
          region: europe-north1
          image: europe-north1-docker.pkg.dev/cloud-418/mope/mope:${{ steps.version.outputs.tag }}